apiVersion: 1
providers:
  - name: myreviewer
    orgId: 1
    folder: MyReviewer
    type: file
    disableDeletion: false
    updateIntervalSeconds: 60
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
